export const LOAD_DATA = 'LOAD_DATA'
export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE'
export const UPDATE_SIDEBAR_VIEW = 'UPDATE_SIDEBAR_VIEW'


export const UPDATE_SELECTED_LIST = 'UPDATE_SELECTED_LIST'
export const UPDATE_DUAL_NUMBER = 'UPDATE_DUAL_NUMBER'

